ac:                                                    #AC计算程序配置
   probe:                                              #状态监测
      app: http://8.142.92.84:18100/api/probe/app                               #运行状态监测
      mem: http://8.142.92.84:18100/api/probe/mem                               #服务器内存监测
      disk: http://8.142.92.84:18100/api/probe/disk                             #服务器磁盘监测
      host: http://8.142.92.84:18100/api/probe/host                             #服务器主机监测
      cpu: http://8.142.92.84:18100/api/probe/cpu                               #服务器 CPU 监测
   FESDiagram: http://8.142.92.84:18100/api/calc/rpc/fesdiagram/pro             #功图计算
   RPM: http://8.142.92.84:18100/api/calc/pcp/rpm                               #螺杆泵转速计产
   communication: http://8.142.92.84:18100/api/calc/plugin/timeeff/comm         #通信时率计算
   run: http://8.142.92.84:18100/api/calc/plugin/timeeff/run                    #运行时率计算
   energy: http://8.142.92.84:18100/api/calc/plugin/energy                      #能耗计算
   totalCalculation: http://8.142.92.84:18100/api/analy/total/well              #全井汇总
threadPool: 
   outerDatabaseSync:
      corePoolSize: 80
      maximumPoolSize: 100
      keepAliveTime: 5
      wattingCount: 0
other: 
   defaultTimeSpan: 0                                #第一次获取功图数据的时间跨度， 0-读取当天数据